---
title: "Advanced R - Term Project"
author: "Ozgur Polat, Bugra Duman"
date: "5/29/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Library Imports

```{r warning=FALSE, message=FALSE}
#install.packages("maps")
#install.packages("sp")
#install.packages("mapdata")
library(shiny)
library(dplyr)
library(tidyverse)
library(DT)
library(shinythemes)
library(knitr)
library(flexdashboard)
library(plotly)
library(tidyverse)
library(dplyr)
library(ggplot2)
library(rvest)
library(magrittr)
library(ggmap)
library(stringr)
library(maps)
library(mapdata)
library(maptools)
```

### Importing The Data

```{r}
protein <- read.csv2("data/protein.csv", header=TRUE, sep=";")
head(protein)

```


### DPLYR and TIDYR Section
```{r message=TRUE, warning=FALSE}


col_to_bind <- as.data.frame(apply(protein[c("Confirmed","Deaths","Recovered","Active","Population")],2,as.numeric))

nums<- col_to_bind %>% transmute(Confirmed = Population * Confirmed / 100, 
  Active = Population * Active / 100,
  Recovered = Population * Recovered / 100,
  Deaths = Population * Deaths / 100)

protein <-subset(protein, select = -c(Confirmed,Deaths,Recovered,Active,Unit..all.except.Population.,X))


protein <- cbind(protein,nums)
```


### Own S4 Class and Method For Each Country
```{r message=TRUE, warning=FALSE}
country <- setClass("country",
                    slots = list(cname = "character",
                                 alcholic_beverages = "numeric",
                                 animal_products = "numeric", 
                                 animal_fats = "numeric",
                                 aquatic_products = "numeric",
                                 cereals = "numeric",
                                 eggs = "numeric",
                                 fish = "numeric",
                                 fruits = "numeric",
                                 meat = "numeric",
                                 milk = "numeric",
                                 offals = "numeric",
                                 oilcrops = "numeric",
                                 pulses = "numeric",
                                 spices = "numeric",
                                 starchy = "numeric",
                                 stimulants = "numeric",
                                 sugar_crops = "numeric",
                                 sugar_and_sweeteners = "numeric",
                                 treenuts = "numeric",
                                 vegetal = "numeric",
                                 vegetable_oils = "numeric",
                                 vegetables = "numeric",
                                 miscellaneous = "numeric",
                                 obesity = "numeric",
                                 undernourished = "numeric",
                                 confirmed = "numeric",
                                 deaths = "numeric",
                                 recovered = "numeric",
                                 active = "numeric",
                                 population = "numeric"))

#CLASS METHOD
setMethod(f = "show", 
          signature = "country", 
          definition = function(object) {
            a <- cat(object@cname, "\n")
            b <- cat("Number of Confirmed Cases:", object@confirmed, "\n")
            c <- cat("Number of Active Cases:", object@active, "\n")
            d <- cat("Number of Recovered Cases:", object@recovered, "\n")
            e <- cat("Number of Deaths:", object@deaths, "\n")
            f <- paste(a,b,c,d,e)
            
            return(f)
          }
)


#Creation of an empty list
countries <- list()


#EACH ROW IN THE DATASET WILL BECOME A COUNTRY OBJECT
#iterating over the dataset
for (row in 1:nrow(protein)) {
  #creation of country objects for each row and appending them to the empty list initialized above
  countries[as.character(protein$Country[row])] <- country(cname = as.character(protein$Country[row]),
                                             alcholic_beverages = as.numeric(protein$Alcoholic.Beverages[row]),
                                             animal_products = as.numeric(protein$Animal.Products[row]), 
                                             animal_fats = as.numeric(protein$Animal.fats[row]),
                                             aquatic_products = as.numeric(protein$Aquatic.Products..Other[row]),
                                             cereals = as.numeric(protein$Cereals...Excluding.Beer[row]),
                                             eggs = as.numeric(protein$Eggs[row]),
                                             fish = as.numeric(protein$Fish..Seafood[row]),
                                             fruits = as.numeric(protein$Fruits...Excluding.Wine[row]),
                                             meat = as.numeric(protein$Meat[row]),
                                             milk = as.numeric(protein$Milk...Excluding.Butter[row]),
                                             offals = as.numeric(protein$Offals[row]),
                                             oilcrops = as.numeric(protein$Oilcrops[row]),
                                             pulses = as.numeric(protein$Pulses[row]),
                                             spices = as.numeric(protein$Spices[row]),
                                             starchy = as.numeric(protein$Starchy.Roots[row]),
                                             stimulants = as.numeric(protein$Stimulants[row]),
                                             sugar_crops = as.numeric(protein$Sugar.Crops[row]),
                                             sugar_and_sweeteners = as.numeric(protein$Sugar...Sweeteners[row]),
                                             treenuts = as.numeric(protein$Treenuts[row]),
                                             vegetal = as.numeric(protein$Vegetal.Products[row]),
                                             vegetable_oils = as.numeric(protein$Vegetable.Oils[row]),
                                             vegetables = as.numeric(protein$Vegetables[row]),
                                             miscellaneous = as.numeric(protein$Miscellaneous[row]),
                                             obesity = as.numeric(protein$Obesity[row]),
                                             undernourished = as.numeric(protein$Undernourished[row]),
                                             confirmed = as.numeric(protein$Confirmed[row]),
                                             deaths = as.numeric(protein$Deaths[row]),
                                             recovered = as.numeric(protein$Recovered[row]),
                                             active = as.numeric(protein$Active[row]),
                                             population = as.numeric(protein$Population[row]))
} 


#As per seen below the object type is S4
typeof(countries$Poland)

#Here the S4 object automatically invokes the defined method
countries$Poland
countries$Turkey
  
#Here the object attribute is called
countries$Turkey@fruits


```

### Shiny With DPLYR and Own Function

```{r pressure, echo=FALSE}

#Creating group for basic stats
#Changing data types to number to compute basic math


plot_it <- function(d, a, b){
    #if else ile farkli plot secenekleri
    myplot <- ggplot(d, aes(x = a, y = b, color= `Total Volume`)) +
      geom_point()
    ggplotly(myplot)
    
    
    #a2 <- select(protein,a)
    #ggplot(data = protein, aes(x = a2, y = b)) +
    #geom_point(colour = "blue") 
}

#plot_it("Confirmed", "Alcoholic")

#Preparation for map plot
#Getting the world map
map.world <- map_data("world")

#getting the supported region names
i <- unique(map.world$region)
i

#getting our country names
k <- as.factor(protein$Country) %>% levels()
k

#comparing them with the supported ones
j <- !(k %in% i)
j

#extracting not supported ones
l <- which(j, arr.ind = FALSE, useNames = TRUE)
l

#Displaying them
for (row in l){
  cat(as.character(protein$Country[row]),"\n")
}

#Recoding
protein$Country <- recode(protein$Country
                                  ,'Antigua and Barbuda' = 'Antigua'
                                  ,'Congo' = 'Republic of Congo'
                                  ,"Cote d'Ivoire" = 'Ivory Coast'
                                  ,'Czechia' = 'Czech Republic'
                                  ,'Iran (Islamic Republic of)' = 'Iran'
                                  ,'Korea' = 'South Korea'
                                  ,'United Kingdom' = 'UK'
                                  ,'United Republic of Tanzania' = 'Tanzania'
                                  ,'United States of America' = 'USA'
                                  )
# LEFT JOIN
map.world_joined <- left_join(map.world, protein, by = c('region' = 'Country'))
identical(map.world,map.world_joined)
head(map.world_joined)

#===================================================
# CREATE FLAG
# - in the map, we're going to highlight
#   the countries with high 'talent competitiveness'
# - Here, we'll create a flag that will
#   indicate whether or not we want to 
#   "fill in" a particular country 
#   on the map
#===================================================
map.world_joined <- map.world_joined %>% mutate(fill_flg = ifelse(is.na(rank),F,T))
head(map.world_joined)

#Creating Country Points For High Cases With Geocodes (Should be Automated)
df.country_points <- data.frame(country = c("USA","Russia"), lon = c(as.numeric(37.09024),as.numeric(61.52401)),lat = c(as.numeric(-95.712891),as.numeric(105.318756)), stringsAsFactors = F)
glimpse(df.country_points)






ggplot() +
  geom_polygon(data = map.world_joined, aes(x = long, y = lat, group = group, fill = fill_flg)) +
  geom_point(data = df.country_points, aes(x = lon, y = lat), color = "#e60000") +
  scale_fill_manual(values = c("#CCCCCC","#e60000")) +
  labs(title = 'Countries with Selected Variable'
       ,subtitle = "source: COVID-19 Healthy Diet Dataset") +
  theme(text = element_text(color = "#FFFFFF")
        ,panel.background = element_rect(fill = "#444444")
        ,plot.background = element_rect(fill = "#444444")
        ,panel.grid = element_blank()
        ,plot.title = element_text(size = 30)
        ,plot.subtitle = element_text(size = 10)
        ,axis.text = element_blank()
        ,axis.title = element_blank()
        ,axis.ticks = element_blank()
        ,legend.position = "none"
        )






protein$Country[162]





map('worldHires')
map('worldHires',"Malta")

str(protein)

```

```{r echo=FALSE}
ui <- fluidPage(
  theme = shinythemes::shinytheme('simplex'),
  titlePanel("Plotter Panel"),
  sidebarLayout(
    sidebarPanel(
      selectInput("first", "Select Country", unique(protein$Country)), 
      selectInput("second", "Select Column", colnames(protein[,-1]))
      #a <-selectInput('Country', 'Select a Country', unique(protein$Country)),
      #b <- select('Nutrition', 'Select Nutririon Type', colnames(protein[,-1])),
      

    ),
    mainPanel(
      tabsetPanel(
        tabPanel("Summary", plotlyOutput('plot')),
        tabPanel("Data Table", DT::DTOutput('table')),
        tabPanel("Boxplot", plotlyOutput('boxplot')),
        tabPanel("World Map", plotlyOutput('mapplot'))
      ),
    )
  )

)

server <- function(input, output, session){
  output$plot <- renderPlotly({
    #myplot <- ggplot(protein, aes_string(x = input$first, y=input$second,colour = protein$Country))
    #ggplotly(myplot)
    newData <- protein  %>%
      filter(Country == input$first)
    myplot <- ggplot(newData, aes(x = `Country`, y = `Active`, color= `Deaths`)) +
      geom_bar(stat = "identity",width = 0.1)+
      theme_bw() +
      theme(axis.text = element_text(size = 12))
    ggplotly(myplot)
  })
  
  output$boxplot <- renderPlotly({
    myplot <- ggplot(protein, aes(x = "", y = input$second)) + 
      geom_boxplot()
    ggplotly(myplot)
  })
  output$mapplot <- renderPlotly({
    data(wrld_simpl)
    myCountries = wrld_simpl@data$NAME %in% protein$Country
    plot(plot(wrld_simpl, col = c(gray(.80), "red")[myCountries+1]))
    ggplotly(map('worldHires',"Malta"))
  })
  
  output$table <- DT::renderDT({
    protein %>%
      filter(Country == input$first) %>%
      select(-1) %>%
      t()
  })


}

shinyApp(ui = ui, server = server)

```
```{r echo=FALSE}
ui <- fluidPage(
  theme = shinythemes::shinytheme('simplex'),
  titlePanel("Country Statistics Panel"),
  sidebarLayout(
    sidebarPanel(
      selectInput("first", "Select Country", unique(protein$Country)), 
      #selectInput("second", "Select Column", colnames(protein[,-1]))
      #a <-selectInput('Country', 'Select a Country', unique(protein$Country)),
      #b <- select('Nutrition', 'Select Nutririon Type', colnames(protein[,-1])),
      

    ),
    mainPanel(
      tabsetPanel(
        tabPanel("Summary", textOutput("summary"))
      ),
    )
  )

)

server <- function(input, output, session){
    outputText <- eventReactive(input$first, {
      show(countries$Afghanistan)
    })
    output$summary <- renderText({
      outputFinal <- outputText()
      isolate(paste(outputFinal))
    })

}

shinyApp(ui = ui, server = server)

```
